### ISSUE TITLE
ProjFS causes BSOD on Windows 10, 1903

### ISSUE THREAD

**Issue by KOHECJIOH** [microsoft/Windows-classic-samples#81] opened 2019-06-21 13:44 UTC
Hi,

I'm currently working on some project using [ProjFS](https://docs.microsoft.com/en-us/windows/desktop/projfs/projected-file-system).

It works great on Windows 10, version 1809, but on the latest 1903 update and under certain circumstances, the `prjflt.sys` driver drops system into BSOD.

To reproduce it, one may follow the following steps:
1) Build Microsoft classic sample for ProjFS: [RegFS](https://github.com/microsoft/Windows-classic-samples/tree/master/Samples/ProjectedFileSystem).
2) Use `regfs.exe` and "mount" RegFS into any directory(let's assume it's `C:\regfs`).
3) Create new empty directory `C:\regfs\XXX`. It's going to create so-called "Full directory" placeholder.
4) Create two files: `C:\regfs\XXX\A.txt` and `C:\regfs\XXX\B.txt`. It's going to create two "Full file" placeholders.
5) Use any move function to rename `A.txt` into `B.txt`(for example, `MoveFile("C:\regfs\XXX\A.txt", "C:\regfs\XXX\B.txt")` from Windows.h).

The last rename leads to system crash with blue screen.
```
Stop code: SYSTEM_SERVICE_EXCEPTION
What failed: prjflt.sys
```

**Comment by rudskoy** [comment] 2019-06-25 10:17
*gentle reminder*

**Comment by oldnewthing** [comment] 2019-06-25 16:44
This looks like a product bug, not a sample bug. You can open a support case with our Developer Support team: https://social.msdn.microsoft.com/Forums/Windowsdesktop/en-us/home

**Comment by abhijeet-gautam** [comment] 2019-07-10 20:01
Thank you @KOHECJIOH for identifying and reporting the issue. 
We are working on a fix and it should be available soon.

**Comment by oldnewthing** [comment] 2019-07-10 20:47
Confirmed as product bug. Closing sample issue.

**Closed by oldnewthing** 2019-07-10 20:47 UTC
Labels: tracking

**Comment by abhijeet-gautam** [comment] 2019-10-04 21:04
This issue manifests when the provider doesn’t implement the optional PRJ_QUERY_FILE_NAME_CB* QueryFileNameCallback (or the HResult OnQueryFileName(string relativePath) in the [managed API](https://github.com/microsoft/ProjFS-Managed-API)).  As a work around this issue, please ensure that your provider implements this callback.
