### ISSUE TITLE
Add a sample for DX11VideoRenderer application (not a dll)

### ISSUE THREAD

**Issue by wighawag** [Microsoft/Windows-classic-samples#33] opened 2018-01-18 12:23 UTC
DX11VideoRenderer sample is building a dll

Any plan to add a sample that either use that dll or make a new one that build an application instead?

**Comment by MaXcomX** [comment] 2018-02-15 21:33
Well.. What do you think of implementing the code in an app where you need this code for, if you really need to? With some programmer skills that would not be to complicated. The whole idea is you can use this library within, for example TopoEdit, to add a DX11VideoRenderer to the topology.

**Comment by oldnewthing** [comment] 2018-11-17 19:31
Duplicate of #8 - the DLL is intended to be used by the topoedit program. See comments in #8 for details.

**Closed by oldnewthing** 2018-11-17 19:31 UTC
